server:
  error:
    include-message: always
spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bank_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration/test
    url: jdbc:h2:mem:bank_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    user: sa
    password: sa
    baselineOnMigrate: true
    configurations: [ 'compileClasspath', 'flywayMigration' ]