server:
  error:
    include-message: always
spring:
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${POSTGRESQL_USERNAME:bank}
    password: ${POSTGRESQL_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration/dev
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/bank}
    user: ${POSTGRESQL_USERNAME:bank}
    password: ${POSTGRESQL_PASSWORD:bank}
    baselineOnMigrate: true
bank:
  exception:
    uri-base: https://api.bank.com.br
    
    